//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atlasws.QService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/WSQBC/QBCDE", ConfigurationName="QService.wsTarifaSoap")]
    public interface wsTarifaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cUsuario del espacio de nombres http://tempuri.org/WSQBC/QBCDE no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSQBC/QBCDE/listaTarifas", ReplyAction="*")]
        atlasws.QService.listaTarifasResponse listaTarifas(atlasws.QService.listaTarifasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cUsuario del espacio de nombres http://tempuri.org/WSQBC/QBCDE no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSQBC/QBCDE/listaMarcas", ReplyAction="*")]
        atlasws.QService.listaMarcasResponse listaMarcas(atlasws.QService.listaMarcasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaTarifasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaTarifas", Namespace="http://tempuri.org/WSQBC/QBCDE", Order=0)]
        public atlasws.QService.listaTarifasRequestBody Body;
        
        public listaTarifasRequest() {
        }
        
        public listaTarifasRequest(atlasws.QService.listaTarifasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WSQBC/QBCDE")]
    public partial class listaTarifasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cTarifa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cMarca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cTipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cVersion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cModelo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cCAMIS;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string cCategoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string cNvaAMIS;
        
        public listaTarifasRequestBody() {
        }
        
        public listaTarifasRequestBody(string cUsuario, string cTarifa, string cMarca, string cTipo, string cVersion, string cModelo, string cCAMIS, string cCategoria, string cNvaAMIS) {
            this.cUsuario = cUsuario;
            this.cTarifa = cTarifa;
            this.cMarca = cMarca;
            this.cTipo = cTipo;
            this.cVersion = cVersion;
            this.cModelo = cModelo;
            this.cCAMIS = cCAMIS;
            this.cCategoria = cCategoria;
            this.cNvaAMIS = cNvaAMIS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaTarifasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaTarifasResponse", Namespace="http://tempuri.org/WSQBC/QBCDE", Order=0)]
        public atlasws.QService.listaTarifasResponseBody Body;
        
        public listaTarifasResponse() {
        }
        
        public listaTarifasResponse(atlasws.QService.listaTarifasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WSQBC/QBCDE")]
    public partial class listaTarifasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement listaTarifasResult;
        
        public listaTarifasResponseBody() {
        }
        
        public listaTarifasResponseBody(System.Xml.Linq.XElement listaTarifasResult) {
            this.listaTarifasResult = listaTarifasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaMarcasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaMarcas", Namespace="http://tempuri.org/WSQBC/QBCDE", Order=0)]
        public atlasws.QService.listaMarcasRequestBody Body;
        
        public listaMarcasRequest() {
        }
        
        public listaMarcasRequest(atlasws.QService.listaMarcasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WSQBC/QBCDE")]
    public partial class listaMarcasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cTarifa;
        
        public listaMarcasRequestBody() {
        }
        
        public listaMarcasRequestBody(string cUsuario, string cTarifa) {
            this.cUsuario = cUsuario;
            this.cTarifa = cTarifa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaMarcasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaMarcasResponse", Namespace="http://tempuri.org/WSQBC/QBCDE", Order=0)]
        public atlasws.QService.listaMarcasResponseBody Body;
        
        public listaMarcasResponse() {
        }
        
        public listaMarcasResponse(atlasws.QService.listaMarcasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WSQBC/QBCDE")]
    public partial class listaMarcasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement listaMarcasResult;
        
        public listaMarcasResponseBody() {
        }
        
        public listaMarcasResponseBody(System.Xml.Linq.XElement listaMarcasResult) {
            this.listaMarcasResult = listaMarcasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsTarifaSoapChannel : atlasws.QService.wsTarifaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsTarifaSoapClient : System.ServiceModel.ClientBase<atlasws.QService.wsTarifaSoap>, atlasws.QService.wsTarifaSoap {
        
        public wsTarifaSoapClient() {
        }
        
        public wsTarifaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsTarifaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTarifaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTarifaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        atlasws.QService.listaTarifasResponse atlasws.QService.wsTarifaSoap.listaTarifas(atlasws.QService.listaTarifasRequest request) {
            return base.Channel.listaTarifas(request);
        }
        
        public System.Xml.Linq.XElement listaTarifas(string cUsuario, string cTarifa, string cMarca, string cTipo, string cVersion, string cModelo, string cCAMIS, string cCategoria, string cNvaAMIS) {
            atlasws.QService.listaTarifasRequest inValue = new atlasws.QService.listaTarifasRequest();
            inValue.Body = new atlasws.QService.listaTarifasRequestBody();
            inValue.Body.cUsuario = cUsuario;
            inValue.Body.cTarifa = cTarifa;
            inValue.Body.cMarca = cMarca;
            inValue.Body.cTipo = cTipo;
            inValue.Body.cVersion = cVersion;
            inValue.Body.cModelo = cModelo;
            inValue.Body.cCAMIS = cCAMIS;
            inValue.Body.cCategoria = cCategoria;
            inValue.Body.cNvaAMIS = cNvaAMIS;
            atlasws.QService.listaTarifasResponse retVal = ((atlasws.QService.wsTarifaSoap)(this)).listaTarifas(inValue);
            return retVal.Body.listaTarifasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        atlasws.QService.listaMarcasResponse atlasws.QService.wsTarifaSoap.listaMarcas(atlasws.QService.listaMarcasRequest request) {
            return base.Channel.listaMarcas(request);
        }
        
        public System.Xml.Linq.XElement listaMarcas(string cUsuario, string cTarifa) {
            atlasws.QService.listaMarcasRequest inValue = new atlasws.QService.listaMarcasRequest();
            inValue.Body = new atlasws.QService.listaMarcasRequestBody();
            inValue.Body.cUsuario = cUsuario;
            inValue.Body.cTarifa = cTarifa;
            atlasws.QService.listaMarcasResponse retVal = ((atlasws.QService.wsTarifaSoap)(this)).listaMarcas(inValue);
            return retVal.Body.listaMarcasResult;
        }
    }
}
