//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atlasws.atlaservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarcaModPet", Namespace="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/")]
    [System.SerializableAttribute()]
    public partial class MarcaModPet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> CategoriaField;
        
        private System.Nullable<long> Cve_negocioField;
        
        private System.Nullable<long> LigaField;
        
        private string MPasswordField;
        
        private string MUsuarioField;
        
        private System.Nullable<long> ModeloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((this.CategoriaField.Equals(value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Cve_negocio {
            get {
                return this.Cve_negocioField;
            }
            set {
                if ((this.Cve_negocioField.Equals(value) != true)) {
                    this.Cve_negocioField = value;
                    this.RaisePropertyChanged("Cve_negocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Liga {
            get {
                return this.LigaField;
            }
            set {
                if ((this.LigaField.Equals(value) != true)) {
                    this.LigaField = value;
                    this.RaisePropertyChanged("Liga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MPassword {
            get {
                return this.MPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.MPasswordField, value) != true)) {
                    this.MPasswordField = value;
                    this.RaisePropertyChanged("MPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MUsuario {
            get {
                return this.MUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.MUsuarioField, value) != true)) {
                    this.MUsuarioField = value;
                    this.RaisePropertyChanged("MUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((this.ModeloField.Equals(value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarcaMod", Namespace="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/")]
    [System.SerializableAttribute()]
    public partial class MarcaMod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> Marca_modField;
        
        private string des_marcaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Marca_mod {
            get {
                return this.Marca_modField;
            }
            set {
                if ((this.Marca_modField.Equals(value) != true)) {
                    this.Marca_modField = value;
                    this.RaisePropertyChanged("Marca_mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string des_marca {
            get {
                return this.des_marcaField;
            }
            set {
                if ((object.ReferenceEquals(this.des_marcaField, value) != true)) {
                    this.des_marcaField = value;
                    this.RaisePropertyChanged("des_marca");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubTipoModPet", Namespace="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/")]
    [System.SerializableAttribute()]
    public partial class SubTipoModPet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> CategoriaField;
        
        private System.Nullable<long> Cve_negocioField;
        
        private System.Nullable<long> LigaField;
        
        private string MPasswordField;
        
        private string MUsuarioField;
        
        private System.Nullable<long> MarcaField;
        
        private System.Nullable<long> ModeloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((this.CategoriaField.Equals(value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Cve_negocio {
            get {
                return this.Cve_negocioField;
            }
            set {
                if ((this.Cve_negocioField.Equals(value) != true)) {
                    this.Cve_negocioField = value;
                    this.RaisePropertyChanged("Cve_negocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Liga {
            get {
                return this.LigaField;
            }
            set {
                if ((this.LigaField.Equals(value) != true)) {
                    this.LigaField = value;
                    this.RaisePropertyChanged("Liga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MPassword {
            get {
                return this.MPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.MPasswordField, value) != true)) {
                    this.MPasswordField = value;
                    this.RaisePropertyChanged("MPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MUsuario {
            get {
                return this.MUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.MUsuarioField, value) != true)) {
                    this.MUsuarioField = value;
                    this.RaisePropertyChanged("MUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((this.MarcaField.Equals(value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((this.ModeloField.Equals(value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarcaMod1", Namespace="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/")]
    [System.SerializableAttribute()]
    public partial class MarcaMod1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> Cve_categoriaField;
        
        private string Descripcion_subtipoField;
        
        private System.Nullable<long> SubtipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Cve_categoria {
            get {
                return this.Cve_categoriaField;
            }
            set {
                if ((this.Cve_categoriaField.Equals(value) != true)) {
                    this.Cve_categoriaField = value;
                    this.RaisePropertyChanged("Cve_categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Descripcion_subtipo {
            get {
                return this.Descripcion_subtipoField;
            }
            set {
                if ((object.ReferenceEquals(this.Descripcion_subtipoField, value) != true)) {
                    this.Descripcion_subtipoField = value;
                    this.RaisePropertyChanged("Descripcion_subtipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Subtipo {
            get {
                return this.SubtipoField;
            }
            set {
                if ((this.SubtipoField.Equals(value) != true)) {
                    this.SubtipoField = value;
                    this.RaisePropertyChanged("Subtipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiModPet", Namespace="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/")]
    [System.SerializableAttribute()]
    public partial class VehiModPet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> CategoriaField;
        
        private System.Nullable<long> Cve_negocioField;
        
        private System.Nullable<long> LigaField;
        
        private string MPasswordField;
        
        private string MUsuarioField;
        
        private System.Nullable<long> MarcaField;
        
        private System.Nullable<long> ModeloField;
        
        private System.Nullable<long> SubTipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((this.CategoriaField.Equals(value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Cve_negocio {
            get {
                return this.Cve_negocioField;
            }
            set {
                if ((this.Cve_negocioField.Equals(value) != true)) {
                    this.Cve_negocioField = value;
                    this.RaisePropertyChanged("Cve_negocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Liga {
            get {
                return this.LigaField;
            }
            set {
                if ((this.LigaField.Equals(value) != true)) {
                    this.LigaField = value;
                    this.RaisePropertyChanged("Liga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MPassword {
            get {
                return this.MPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.MPasswordField, value) != true)) {
                    this.MPasswordField = value;
                    this.RaisePropertyChanged("MPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MUsuario {
            get {
                return this.MUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.MUsuarioField, value) != true)) {
                    this.MUsuarioField = value;
                    this.RaisePropertyChanged("MUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((this.MarcaField.Equals(value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((this.ModeloField.Equals(value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> SubTipo {
            get {
                return this.SubTipoField;
            }
            set {
                if ((this.SubTipoField.Equals(value) != true)) {
                    this.SubTipoField = value;
                    this.RaisePropertyChanged("SubTipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiMod", Namespace="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/")]
    [System.SerializableAttribute()]
    public partial class VehiMod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cve_amisField;
        
        private System.Nullable<long> cve_categoriaField;
        
        private System.Nullable<long> cve_vehiculoField;
        
        private string des_vehiculoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cve_amis {
            get {
                return this.cve_amisField;
            }
            set {
                if ((object.ReferenceEquals(this.cve_amisField, value) != true)) {
                    this.cve_amisField = value;
                    this.RaisePropertyChanged("cve_amis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> cve_categoria {
            get {
                return this.cve_categoriaField;
            }
            set {
                if ((this.cve_categoriaField.Equals(value) != true)) {
                    this.cve_categoriaField = value;
                    this.RaisePropertyChanged("cve_categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> cve_vehiculo {
            get {
                return this.cve_vehiculoField;
            }
            set {
                if ((this.cve_vehiculoField.Equals(value) != true)) {
                    this.cve_vehiculoField = value;
                    this.RaisePropertyChanged("cve_vehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string des_vehiculo {
            get {
                return this.des_vehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.des_vehiculoField, value) != true)) {
                    this.des_vehiculoField = value;
                    this.RaisePropertyChanged("des_vehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModMS_pet", Namespace="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/")]
    [System.SerializableAttribute()]
    public partial class ModMS_pet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> CategoriaField;
        
        private System.Nullable<long> Cve_negocioField;
        
        private System.Nullable<long> LigaField;
        
        private string MPasswordField;
        
        private string MUsuarioField;
        
        private System.Nullable<long> MarcaField;
        
        private System.Nullable<long> SubTipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((this.CategoriaField.Equals(value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Cve_negocio {
            get {
                return this.Cve_negocioField;
            }
            set {
                if ((this.Cve_negocioField.Equals(value) != true)) {
                    this.Cve_negocioField = value;
                    this.RaisePropertyChanged("Cve_negocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Liga {
            get {
                return this.LigaField;
            }
            set {
                if ((this.LigaField.Equals(value) != true)) {
                    this.LigaField = value;
                    this.RaisePropertyChanged("Liga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MPassword {
            get {
                return this.MPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.MPasswordField, value) != true)) {
                    this.MPasswordField = value;
                    this.RaisePropertyChanged("MPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MUsuario {
            get {
                return this.MUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.MUsuarioField, value) != true)) {
                    this.MUsuarioField = value;
                    this.RaisePropertyChanged("MUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((this.MarcaField.Equals(value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> SubTipo {
            get {
                return this.SubTipoField;
            }
            set {
                if ((this.SubTipoField.Equals(value) != true)) {
                    this.SubTipoField = value;
                    this.RaisePropertyChanged("SubTipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloMS", Namespace="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/")]
    [System.SerializableAttribute()]
    public partial class ModeloMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> ModeloField;
        
        private System.Nullable<long> cve_categoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((this.ModeloField.Equals(value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> cve_categoria {
            get {
                return this.cve_categoriaField;
            }
            set {
                if ((this.cve_categoriaField.Equals(value) != true)) {
                    this.cve_categoriaField = value;
                    this.RaisePropertyChanged("cve_categoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/", ConfigurationName="atlaservice.WS_CatXModImpl")]
    public interface WS_CatXModImpl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/WS_CatXModImpl#W" +
            "S_ModMarcas?KFtMY29tL3VuaXBhYXMvc2VndXJvc19hdGxhc19zYS9XU19DYXRYTW9kL01hcmNhTW9k" +
            "UGV0OylbTGNvbS91bmlwYWFzL3NlZ3Vyb3NfYXRsYXNfc2EvV1NfQ2F0WE1vZC9NYXJjYU1vZDs=", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(object), Action="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/WS_CatXModImpl#W" +
            "S_ModMarcas?KFtMY29tL3VuaXBhYXMvc2VndXJvc19hdGxhc19zYS9XU19DYXRYTW9kL01hcmNhTW9k" +
            "UGV0OylbTGNvbS91bmlwYWFzL3NlZ3Vyb3NfYXRsYXNfc2EvV1NfQ2F0WE1vZC9NYXJjYU1vZDs=", Name="idoox-java-mapping.java.lang.Exception", Namespace="http://systinet.com/xsd/SchemaTypes/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        atlasws.atlaservice.MarcaMod[] WS_ModMarcas(atlasws.atlaservice.MarcaModPet[] P_XHML_IN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/WS_CatXModImpl#W" +
            "S_ModSubTipos?KFtMY29tL3VuaXBhYXMvc2VndXJvc19hdGxhc19zYS9XU19DYXRYTW9kL1N1YlRpcG" +
            "9Nb2RQZXQ7KVtMY29tL3VuaXBhYXMvc2VndXJvc19hdGxhc19zYS9XU19DYXRYTW9kL01hcmNhTW9kMT" +
            "s=", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(object), Action="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/WS_CatXModImpl#W" +
            "S_ModSubTipos?KFtMY29tL3VuaXBhYXMvc2VndXJvc19hdGxhc19zYS9XU19DYXRYTW9kL1N1YlRpcG" +
            "9Nb2RQZXQ7KVtMY29tL3VuaXBhYXMvc2VndXJvc19hdGxhc19zYS9XU19DYXRYTW9kL01hcmNhTW9kMT" +
            "s=", Name="idoox-java-mapping.java.lang.Exception", Namespace="http://systinet.com/xsd/SchemaTypes/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        atlasws.atlaservice.MarcaMod1[] WS_ModSubTipos(atlasws.atlaservice.SubTipoModPet[] P_XHML_IN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/WS_CatXModImpl#W" +
            "S_ModVehiculos?KFtMY29tL3VuaXBhYXMvc2VndXJvc19hdGxhc19zYS9XU19DYXRYTW9kL1ZlaGlNb" +
            "2RQZXQ7KVtMY29tL3VuaXBhYXMvc2VndXJvc19hdGxhc19zYS9XU19DYXRYTW9kL1ZlaGlNb2Q7", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(object), Action="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/WS_CatXModImpl#W" +
            "S_ModVehiculos?KFtMY29tL3VuaXBhYXMvc2VndXJvc19hdGxhc19zYS9XU19DYXRYTW9kL1ZlaGlNb" +
            "2RQZXQ7KVtMY29tL3VuaXBhYXMvc2VndXJvc19hdGxhc19zYS9XU19DYXRYTW9kL1ZlaGlNb2Q7", Name="idoox-java-mapping.java.lang.Exception", Namespace="http://systinet.com/xsd/SchemaTypes/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        atlasws.atlaservice.VehiMod[] WS_ModVehiculos(atlasws.atlaservice.VehiModPet[] P_XHML_IN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/WS_CatXModImpl#W" +
            "S_Modelos_MS?KFtMY29tL3VuaXBhYXMvc2VndXJvc19hdGxhc19zYS9XU19DYXRYTW9kL01vZE1TX3B" +
            "ldDspW0xjb20vdW5pcGFhcy9zZWd1cm9zX2F0bGFzX3NhL1dTX0NhdFhNb2QvTW9kZWxvTVM7", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(object), Action="http://systinet.com/wsdl/com/unipaas/seguros_atlas_sa/WS_CatXMod/WS_CatXModImpl#W" +
            "S_Modelos_MS?KFtMY29tL3VuaXBhYXMvc2VndXJvc19hdGxhc19zYS9XU19DYXRYTW9kL01vZE1TX3B" +
            "ldDspW0xjb20vdW5pcGFhcy9zZWd1cm9zX2F0bGFzX3NhL1dTX0NhdFhNb2QvTW9kZWxvTVM7", Name="idoox-java-mapping.java.lang.Exception", Namespace="http://systinet.com/xsd/SchemaTypes/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        atlasws.atlaservice.ModeloMS[] WS_Modelos_MS(atlasws.atlaservice.ModMS_pet[] P_XHML_IN);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_CatXModImplChannel : atlasws.atlaservice.WS_CatXModImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_CatXModImplClient : System.ServiceModel.ClientBase<atlasws.atlaservice.WS_CatXModImpl>, atlasws.atlaservice.WS_CatXModImpl {
        
        public WS_CatXModImplClient() {
        }
        
        public WS_CatXModImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_CatXModImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_CatXModImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_CatXModImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public atlasws.atlaservice.MarcaMod[] WS_ModMarcas(atlasws.atlaservice.MarcaModPet[] P_XHML_IN) {
            return base.Channel.WS_ModMarcas(P_XHML_IN);
        }
        
        public atlasws.atlaservice.MarcaMod1[] WS_ModSubTipos(atlasws.atlaservice.SubTipoModPet[] P_XHML_IN) {
            return base.Channel.WS_ModSubTipos(P_XHML_IN);
        }
        
        public atlasws.atlaservice.VehiMod[] WS_ModVehiculos(atlasws.atlaservice.VehiModPet[] P_XHML_IN) {
            return base.Channel.WS_ModVehiculos(P_XHML_IN);
        }
        
        public atlasws.atlaservice.ModeloMS[] WS_Modelos_MS(atlasws.atlaservice.ModMS_pet[] P_XHML_IN) {
            return base.Channel.WS_Modelos_MS(P_XHML_IN);
        }
    }
}
